email_configuration:
  smtp_server:  "localhost"
  port: "465"
  sender_email: "sender@test.org"
  receiver_email: "receiver@test.org"

API_configuration:
  API_key: "123456ABCDE7890"
  user_id: "12345678"
  is_group: True
  saved_search_name: "Last week's new items"