email_configuration:
  smtp_server:  "localhost"
  port: "465"
  sender_email: "sender@test.org"
  receiver_email: "receiver@test.org"

API_configuration:
  #API_key: "123456ABCDE7890"
  API_key: "AwmIsxfG9L39daG3z8tSVcfr"
  #user_id: "12345678"
  user_id: "8267074"
  is_group: True
  period_in_days: 7